Host.create(:id => 22, :name => "Wal-Mart Stores", :category_id => 13, :user_id => 5)
Host.create(:id => 23, :name => "Exxon Mobil", :category_id => 14, :user_id => 5)
Host.create(:id => 24, :name => "Chevron", :category_id => 14, :user_id => 5)
Host.create(:id => 25, :name => "Phillips 66", :category_id => 14, :user_id => 5)
Host.create(:id => 26, :name => "Berkshire Hathaway", :category_id => 17, :user_id => 5)
Host.create(:id => 27, :name => "Apple", :category_id => 16, :user_id => 5)
Host.create(:id => 28, :name => "General Motors", :category_id => 16, :user_id => 5)
Host.create(:id => 29, :name => "General Electric", :category_id => 15, :user_id => 5)
Host.create(:id => 30, :name => "Valero Energy", :category_id => 14, :user_id => 5)
Host.create(:id => 31, :name => "Ford Motor", :category_id => 16, :user_id => 5)
